# Generated by Django 4.2.2 on 2023-07-24 06:35

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('talk', '잡담'), ('Q&A', '패션질문')], max_length=50, null=True)),
                ('title', models.CharField(max_length=50)),
                ('contents', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article')),
            ],
        ),
    ]
