# Generated by Django 4.2.2 on 2023-07-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('notice', '공지사항'), ('talk', '잡담'), ('qna', '패션질문')], max_length=50, null=True),
        ),
    ]
