# Generated by Django 4.2.2 on 2023-07-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mdate',
        ),
    ]
