# Generated by Django 4.2.2 on 2023-07-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
